In [1]:
import numpy as np

In [2]:
#sigmod function
def sigmod(x):
    return 1/(1+np.exp(-x))

In [3]:
#sigmod derivation
def sigmod_derivative(x):
    return x*(1-x)

In [4]:
#input data
traning_data=np.array([[0,0,1],
                       [1,1,1],
                       [1,0,1],
                        [0,1,1]])

In [5]:
traning_data

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [6]:
#output data
training_outputs=np.array([[0,1,1,0]]).T
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [7]:
np.random.seed(1)

In [8]:
synaptic_weights=2*np.random.random((3,1))-1

In [9]:
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [10]:
for iteration in range(1000):
    input_layer=traning_data
    outputs=sigmod(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustment=error*sigmod_derivative(outputs)
    synaptic_weights+=np.dot(input_layer.T,adjustment)

In [11]:
synaptic_weights

array([[ 7.26283009],
       [-0.21614618],
       [-3.41703015]])

In [12]:
outputs

array([[0.03178421],
       [0.97414645],
       [0.97906682],
       [0.02576499]])